### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rbutleriii** [NCBI-Hackathons/phenotypeXpression#40]
We are getting the other type of error on some queries, which should not have less than two gds. Here is the traceback:
```
Traceback (most recent call last):
  File "run_phenox.py", line 52, in <module>
    run(args)
  File "run_phenox.py", line 13, in run
    phenox.subtype()
  File "/Users/rbutler/Github/phenotypeXpression/phenox/phenox.py", line 138, in subtype
    mesh_term['name']
  File "/Users/rbutler/Github/phenotypeXpression/phenox/phenox.py", line 45, in _get_geo_datasets
    pubmed_dict, gds_dict, cluster_dict, meta_dict = geo.get_all_geo_data(mesh_term)
  File "/Users/rbutler/Github/phenotypeXpression/phenox/geo_data.py", line 431, in get_all_geo_data
    geo_to_pid_dict = self.get_pubmed_ids(gds_dict)
  File "/Users/rbutler/Github/phenotypeXpression/phenox/geo_data.py", line 264, in get_pubmed_ids
    el['IdList'][0]: el['LinkSetDb'][0]['Link'][0]['Id'] for el in pid_list
  File "/Users/rbutler/Github/phenotypeXpression/phenox/geo_data.py", line 264, in <dictcomp>
    el['IdList'][0]: el['LinkSetDb'][0]['Link'][0]['Id'] for el in pid_list
IndexError: list index out of range
```
Will look at if I find time this weekend or Monday.

**Comment by rbutleriii** [comment]
Happens with "Apnea"

**Comment by lucylw** [comment]
Addressed in https://github.com/NCBI-Hackathons/phenotypeXpression/commit/ac41c6d8acf6140d0999013a8607b82d4790b213
