### ISSUE TITLE
DockerHub Build issue

### ISSUE THREAD

**Issue by rbutleriii** [NCBI-Hackathons/phenotypeXpression#46]
After rebuilding the Dockerhub successfully, I get the following error when running
```
(phenoX) root@b9a33eb92ab8:/phenoX/phenotypeXpression# python run_phenox.py -e A.N.Other@example.com Apnea
Traceback (most recent call last):
  File "run_phenox.py", line 4, in <module>
    from phenox.phenox import PhenoX
  File "/phenoX/phenotypeXpression/phenox/phenox.py", line 12, in <module>
    from phenox.geo_data import GEOQuery
  File "/phenoX/phenotypeXpression/phenox/geo_data.py", line 24, in <module>
    from rpy2.robjects import pandas2ri, default_converter
  File "/root/miniconda3/envs/phenoX/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/root/miniconda3/envs/phenoX/lib/python3.6/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: libicuuc.so.58: cannot open shared object file: No such file or directory
```

**Comment by rbutleriii** [comment]
Appears to be an `rpy2` issue, or more specifically, an incompatibility between `conda-defaults` and `conda-forge`:
https://github.com/ContinuumIO/anaconda-issues/issues/1403
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/myBjZaaAoDI
Trying to use `conda-forge` as much as possible, as some packages (`r-pvclust`) are not available in `conda-defaults`.

**Comment by rbutleriii** [comment]
Resolved by changing `setup.sh` to specify `conda-forge` version of `matplotlib`. All future conda packages containing non-python code need to be `conda-forge` versions until `conda-forge` and `conda-defaults` resolve the compatibility issue, or until `conda-defaults` has all of the packages we need.
